version: "3"

services:
  faucet-ubtc:
    container_name: faucet-ubtc
    image: ghcr.io/tendermint/faucet
    volumes:
      - ~/faucet/ununifid:/usr/local/bin/ununifid
      - ~/.ununifi:/root/.ununifi
    command: faucet --cli-name ununifid --denoms ubtc --keyring-backend test --account-name faucet --port 7000 --credit-amount=100 --max-credit=99
    # ports:
    #   - 7000:7000
    network_mode: host
    restart: always
  faucet-uguu:
    container_name: faucet-uguu
    image: ghcr.io/tendermint/faucet
    volumes:
      - ~/faucet/ununifid:/usr/local/bin/ununifid
      - ~/.ununifi:/root/.ununifi
    command: faucet --cli-name ununifid --denoms uguu --keyring-backend test --account-name faucet --port 7002 --credit-amount=2000000 --max-credit=1999999
    # ports:
    #   - 7002:7002
    network_mode: host
    restart: always
  faucet-ununifi:
    container_name: faucet-jpu
    image: ghcr.io/tendermint/faucet
    volumes:
      - ~/faucet/ununifid:/usr/local/bin/ununifid
      - ~/.ununifi:/root/.ununifi
    command: faucet --cli-name ununifid --denoms jpu --keyring-backend test --account-name faucet --port 7004 --credit-amount=10 --max-credit=9
    # ports:
    #   - 7004:7004
    network_mode: host
    restart: always
  faucet-ueth:
    container_name: faucet-ueth
    image: ghcr.io/tendermint/faucet
    volumes:
      - ~/faucet/ununifid:/usr/local/bin/ununifid
      - ~/.ununifi:/root/.ununifi
    command: faucet --cli-name ununifid --denoms ueth --keyring-backend test --account-name faucet --port 7006 --credit-amount=1000 --max-credit=999
    # ports:
    #   - 7006:7006
    network_mode: host
    restart: always
  faucet-euu:
    container_name: faucet-euu
    image: ghcr.io/tendermint/faucet
    volumes:
      - ~/faucet/ununifid:/usr/local/bin/ununifid
      - ~/.ununifi:/root/.ununifi
    command: faucet --cli-name ununifid --denoms euu --keyring-backend test --account-name faucet --port 7008 --credit-amount=10 --max-credit=9
    # ports:
    #   - 7008:7008
    network_mode: host
    restart: always
  nginx:
    container_name: faucet-nginx
    image: nginx
    volumes:
      - ~/faucet/nginx.conf:/etc/nginx/nginx.conf
    # ports:
    #   - 8000:8000
    #   - 8002:8002
    #   - 8004:8004
    #   - 8006:8006
    #   - 8008:8008
    network_mode: host
    restart: always
